name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      # Checks out the code from the repository
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      # Installs dependencies
    - run: npm run build --if-present
      # Runs build script if it exists
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.4
      with:
        jestArgs: # optional arguments for Jest
        # Example:
        # jestArgs: '--coverage' # Uncomment and adjust as needed
